version: '3.9'

services:
  wl-1:
    restart: unless-stopped
    image: likewhatevs/perfstuff:noisy-workload
    cpuset: "0-3,16-19"
    environment:
      # SLEEP: true
      - W_PCT=30
      - N_PCT=30

  wl-2:
    restart: unless-stopped
    image: likewhatevs/perfstuff:noisy-workload
    cpuset: "4-7,20-23"
    environment:
      # SLEEP: true
      - W_PCT=30
      - N_PCT=30

  wl-3:
    restart: unless-stopped
    image: likewhatevs/perfstuff:noisy-workload
    cpuset: "8-11,24-27"
    environment:
      # SLEEP: true
      - W_PCT=30
      - N_PCT=30

  wl-4:
    restart: unless-stopped
    image: likewhatevs/perfstuff:noisy-workload
    cpuset: "12-15,28-31"
    environment:
      # SLEEP: true
      - W_PCT=30
      - N_PCT=30


